"""add assignment association table

Revision ID: 8f9eeff907b8
Revises: 1917894923a7
Create Date: 2024-07-08 01:30:41.298710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9eeff907b8'
down_revision = '1917894923a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('employee_meetings')
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.VARCHAR(), nullable=True))
    op.create_table('employee_meetings',
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_employee_meetings_employee_id_employees'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='fk_employee_meetings_meeting_id_meetings'),
    sa.PrimaryKeyConstraint('employee_id', 'meeting_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_assignments_employee_id_employees'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_assignments_project_id_projects'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
